export enum RouteName {
  Dashboard = 'dashboard',
  Post = 'post',
  ViewPost = 'view-posts',
  EditPost = 'edit-posts',
  EditCategory = 'edit-category',
  Note = 'note',
  ViewNote = 'view-notes',
  EditNote = 'edit-notes',
  Comment = 'comment',
  Page = 'page',
  ListPage = 'page-list',
  EditPage = 'page-edit',
  Say = 'say',
  ListSay = 'say-list',
  EditSay = 'say-edit',
  Project = 'project',
  ListProject = 'project-list',

  EditProject = 'project-edit',
  Friend = 'friends',
  File = 'files',
  Analyze = 'analyze',
  Setting = 'setting',
  Profile = 'setting-profile',
  System = 'setting-system',
  Security = 'setting-security',
  Reset = 'reset',
  Other = 'other',
  Backup = 'backup',
  Markdown = 'markdown',
  Optimize = 'optimize',
  Login = 'login',
  Home = 'home',
}
