export enum RouteName {
  Dashboard = 'dashboard',
  Post = 'post',
  ViewPost = 'view-posts',
  EditPost = 'edit-posts',
  EditCategory = 'edit-category',
  Note = 'note',
  ViewNote = 'view-notes',
  EditNote = 'edit-notes',
  Topic = 'topic',
  Comment = 'comment',
  Page = 'page',

  ListPage = 'page-list',
  EditPage = 'page-edit',
  Say = 'say',
  ListSay = 'say-list',
  Project = 'project',
  ListProject = 'project-list',

  EditProject = 'project-edit',
  Friend = 'friends',
  File = 'files',
  Analyze = 'analyze',
  Setting = 'setting',
  Profile = 'setting-profile',
  System = 'setting-system',
  Security = 'setting-security',
  Reset = 'reset',
  Backup = 'backup',
  Markdown = 'markdown',
  Subscribe = 'subscribe',
  Cron = 'cron',
  Optimize = 'optimize',
  Login = 'login',
  Home = 'home',
  Setup = 'setup',
  ListShortHand = 'shorthand',
  Snippet = 'snippet',
  Webhook = 'webhook',

  AssetTemplate = 'asset-template',

  Ai = 'ai',
  AiSummary = 'ai-summary',
  AiTranslation = 'ai-translation',

  Maintain = 'maintain',
  Other = 'other',
  Reader = 'reader',
  Draft = 'draft',
}
